language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - (cd haret-client && cargo build --verbose)
  - (cd haret-client && cargo test --verbose)
  - (cd haret-cli-client && cargo build --verbose)
  - (cd haret-cli-client && cargo test --verbose)
