[package]
name = "v2r2"
version = "0.1.0"
authors = ["Andrew J. Stone <andrewstone@vmware.com>"]

[dependencies]
serde = "*"
serde_macros = "*"
serde_json = "*"
libc = "0.1"
rustc-serialize = "*"
time = "*"
uuid = "0.1"
rand = "*"

fsm = { path = "../fsm" }
orset = { path = "../orset"}

[dependencies.mio]
git = "https://github.com/carllerche/mio.git"

[dependencies.msgpack]
git = "https://github.com/mneumann/rust-msgpack.git"

[dependencies.streaming-stats]
git = "git://github.com/BurntSushi/rust-stats"

[[bin]]
name = "v2r2"
path = "src/bin/v2r2.rs"

[[bin]]
name = "v2r2-cli-client"
path = "src/bin/v2r2-cli-client.rs"

[[bin]]
name = "v2r2-admin"
path = "src/bin/v2r2-admin.rs"

[[bin]]
name = "devconfig"
path = "src/bin/devconfig.rs"

[[bin]]
name = "debugger_cli"
path = "tests/debugger_cli.rs"

