[package]
name = "v2r2"
version = "0.1.0"
authors = ["Andrew J. Stone <andrewstone@vmware.com>"]

[dependencies]
serde = "*"
serde_macros = "*"
serde_json = "*"
libc = "0.1"
rustc-serialize = "*"
time = "*"
uuid = "0.1"
rand = "*"

fsm = { path = "../fsm" }
orset = { path = "../orset"}

[dependencies.mio]
git = "https://github.com/carllerche/mio.git"

[dependencies.msgpack]
git = "https://github.com/mneumann/rust-msgpack.git"
