[package]
name = "v2r2"
version = "0.1.0"
authors = ["Andrew J. Stone <andrewstone@vmware.com>"]

[dependencies.mio]
git = "https://github.com/carllerche/mio.git"

[dev-dependencies]
quickcheck = "*"
rand = "*"
